version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Base64 Encode Files and Send to Lambda
          command: |
            # Base64 encode both files
            job_file_base64=$(base64 -w 0 nomad_job.hcl)
            vars_file_base64=$(base64 -w 0 testing.vars)

            # Create the payload for Lambda (using JSON)
            curl -X POST \
              -H "Content-Type: application/json" \
              --data '{
                "job_file_base64": "'"$job_file_base64"'",
                "vars_file_base64": "'"$vars_file_base64"'"
              }' \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
