version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Combine HCL files with SPLIT and Upload to Lambda
          command: |
            # Combine nomad_job.hcl and testing.vars with a precise SPLIT delimiter
            cat nomad_job.hcl > combined_file
            printf '===SPLIT===\n' >> combined_file   # Ensure no extra newlines are added
            cat testing.vars >> combined_file

            # Display the combined file content for debugging
            echo "Combined file content:"
            cat combined_file

            # Send the combined file to Lambda via API Gateway
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_file \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
