version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Combine HCL files with SPLIT and send to Lambda
          command: |
            # Combine files with delimiter
            cat nomad_job.hcl > combined_file
            echo '===SPLIT===' >> combined_file
            cat testing.vars >> combined_file

            # Debug: Print the contents of the combined file
            echo "Combined file contents before encoding:"
            cat combined_file

            # Base64 encode the combined file
            base64 --wrap=0 combined_file > combined_file_base64

            # Send the base64 encoded combined file to Lambda
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_file_base64 \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
