version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Combine HCL files with SPLIT and Upload to Lambda
          command: |
            # Combine files without adding extra newlines
            cat nomad_job.hcl > combined_file
            echo -n '===SPLIT===' >> combined_file   # Use -n to avoid newline
            cat testing.vars >> combined_file

            # Debug combined file content
            echo "Combined file content:"
            hexdump -C combined_file

            # Send the combined file to Lambda
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_file \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
