version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Combine HCL files and Upload to Lambda
          command: |
            # Combine nomad_job.hcl and testing.vars into a single HCL file
            cat nomad_job.hcl testing.vars > combined_nomad_job.hcl

            # Send the combined HCL file to Lambda via API Gateway
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_nomad_job.hcl \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
