version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Combine HCL files with SPLIT and Upload to Lambda
          command: |
            # Combine nomad_job.hcl and testing.vars with a SPLIT delimiter
            cat nomad_job.hcl > combined_file
            echo -e '===SPLIT===\n' >> combined_file   # Ensure the delimiter has a newline after it
            cat testing.vars >> combined_file

            # Send the combined file to Lambda via API Gateway
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_file \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
