version: 2.1

jobs:
  dynamic-deploy:
    steps:
      - checkout
      - run:
          name: Detect Modified Job Files
          command: |
            # Detect the modified .hcl and .vars files in the branch
            JOB_FILE=$(git diff --name-only origin/main $CIRCLE_BRANCH | grep -E '\.hcl$')
            VARS_FILE=$(git diff --name-only origin/main $CIRCLE_BRANCH | grep -E '\.vars$')

            # Ensure at least one file is found
            if [ -z "$JOB_FILE" ] || [ -z "$VARS_FILE" ]; then
              echo "Error: No .hcl or .vars files modified in this branch."
              exit 1
            fi

            # Pass the detected files as environment variables
            echo "export JOB_FILE=$JOB_FILE" >> $BASH_ENV
            echo "export VARS_FILE=$VARS_FILE" >> $BASH_ENV

      - run:
          name: Process Job and Vars Files
          command: |
            # Convert files to UTF-8 Encoding
            iconv -f $(file -bi $JOB_FILE | sed 's/.*charset=//') -t UTF-8 $JOB_FILE -o job_utf8.hcl
            iconv -f $(file -bi $VARS_FILE | sed 's/.*charset=//') -t UTF-8 $VARS_FILE -o vars_utf8.vars
            mv job_utf8.hcl $JOB_FILE
            mv vars_utf8.vars $VARS_FILE

            # Base64 encode without line breaks
            base64 $JOB_FILE | tr -d '\n' | sed -E 's/(.{76})/\1\n/g' > job_base64.txt
            base64 $VARS_FILE | tr -d '\n' | sed -E 's/(.{76})/\1\n/g' > vars_base64.txt

            # Combine the base64 encoded files with a delimiter
            cat job_base64.txt > combined_file
            echo '===SPLIT===' >> combined_file
            cat vars_base64.txt >> combined_file

      # - run:
      #     name: Deploy to Lambda
      #     command: |
      #       curl -X POST \
      #         -H "Content-Type: application/octet-stream" \
      #         --data-binary @combined_file \
      #         https://aj3ah32u35.execute-api.ap-southeast-1.amazonaws.com/staging/test-script

workflows:
  version: 2
  dynamic-workflow:
    jobs:
      - dynamic-deploy:
          filters:
            branches:
              ignore: main
