version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Combine HCL files with SPLIT and Upload to Lambda
          command: |
            # Combine nomad_job.hcl and testing.vars with an explicit SPLIT delimiter
            cat nomad_job.hcl > combined_file
            echo '===SPLIT===' >> combined_file  # Avoid -e option to simplify
            cat testing.vars >> combined_file

            # Debug: Print combined file content for verification
            echo "Combined File Content:"
            cat combined_file

            # Send the combined file to Lambda via API Gateway
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_file \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
