jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Base64 Encode HCL Files and Send to Lambda
          command: |
            # Base64 encode the files
            base64 nomad_job.hcl > nomad_job_base64.txt
            base64 testing.vars > testing_vars_base64.txt

            # Combine the base64 encoded files with the delimiter
            cat nomad_job_base64.txt > combined_file
            echo '===SPLIT===' >> combined_file
            cat testing_vars_base64.txt >> combined_file

            # Send the combined base64 file to Lambda
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_file \
              https://hds3pu35e7.execute-api.ap-south-1.amazonaws.com/dev/test-script

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
