version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  dynamic-deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Detect Modified Job Files
          command: |
            JOB_FILE=$(git diff --name-only origin/main $CIRCLE_BRANCH | grep -E '\.hcl$' || true)
            VARS_FILE=$(git diff --name-only origin/main $CIRCLE_BRANCH | grep -E '\.vars$' || true)

            if [[ -z "$JOB_FILE" || -z "$VARS_FILE" ]]; then
              echo "Error: No .hcl or .vars files modified in this branch."
              exit 1
            fi

            echo "export JOB_FILE=$JOB_FILE" >> $BASH_ENV
            echo "export VARS_FILE=$VARS_FILE" >> $BASH_ENV

      - run:
          name: Ensure UTF-8 Encoding for Files and Base64 Encode
          command: |
            source $BASH_ENV

            # Convert to UTF-8 only if necessary
            if [[ $(file -bi "$JOB_FILE" | sed 's/.*charset=//') != "utf-8" ]]; then
              iconv -f $(file -bi "$JOB_FILE" | sed 's/.*charset=//') -t UTF-8 "$JOB_FILE" -o "job_utf8.hcl"
              mv "job_utf8.hcl" "$JOB_FILE"
            fi

            if [[ $(file -bi "$VARS_FILE" | sed 's/.*charset=//') != "utf-8" ]]; then
              iconv -f $(file -bi "$VARS_FILE" | sed 's/.*charset=//') -t UTF-8 "$VARS_FILE" -o "vars_utf8.vars"
              mv "vars_utf8.vars" "$VARS_FILE"
            fi

            # Base64 encode without line breaks
            base64 -w 0 "$JOB_FILE" > job_base64.txt
            base64 -w 0 "$VARS_FILE" > vars_base64.txt

            # Combine with delimiters
            cat job_base64.txt > combined_file
            echo '===SPLIT===' >> combined_file
            cat vars_base64.txt >> combined_file

      - run:
          name: Deploy to Lambda
          command: |
            set -e  # Exit on any error
            curl -X POST \
              -H "Content-Type: application/octet-stream" \
              --data-binary @combined_file \
              https://jqfp3e37rh.execute-api.ap-southeast-1.amazonaws.com/staging/nomad-job || {
                echo "❌ Deployment failed!"
                exit 1
              }
            echo "✅ Deployment successful!"

workflows:
  version: 2
  dynamic-workflow:
    jobs:
      - dynamic-deploy:
          filters:
            branches:
              ignore: main
