version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Ensure UTF-8 Encoding for Files and Base64 Encode
          command: |
            # Convert files to UTF-8 Encoding
            iconv -f $(file -bi nomad_job.hcl | sed 's/.*charset=//') -t UTF-8 nomad_job.hcl -o nomad_job_utf8.hcl
            iconv -f $(file -bi testing.vars | sed 's/.*charset=//') -t UTF-8 testing.vars -o testing_utf8.vars
            mv nomad_job_utf8.hcl nomad_job.hcl
            mv testing_utf8.vars testing.vars
            # Base64 encode without line breaks
            base64 nomad_job.hcl | tr -d '\n' | sed -E 's/(.{76})/\1\n/g' > nomad_job_base64.txt
            base64 testing.vars | tr -d '\n' | sed -E 's/(.{76})/\1\n/g' > testing_vars_base64.txt
            # Combine the base64 encoded files with a delimiter
            cat nomad_job_base64.txt > combined_file
            echo '===SPLIT===' >> combined_file
            cat testing_vars_base64.txt >> combined_file
            # Send the combined base64 file to Lambda
            # curl -X POST \
            #   -H "Content-Type: application/octet-stream" \
            #   --data-binary @combined_file \
            #   https://aj3ah32u35.execute-api.ap-southeast-1.amazonaws.com/staging/test-script


workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
